### ISSUE TITLE
How to save 3D models 

### ISSUE THREAD

**Issue by rohaantahir** [ZijingPeng/3d-cgan#1]
Hey! I want to cite your work in my research. I want to ask how to save the generated model from test.py in 3D format and how to evaluate it with the ground truth. Kindly guide me in this regard.

Thanks

**Comment by ZijingPeng** [comment]
Sorry to apply late! Following is a test script I once wrote, I am not sure whether it can help you.

https://drive.google.com/open?id=1lNvPAEv4V74NNWj7zOeMXhMOdyWjn7kp
